### ISSUE TITLE
v5.1.6 introduces breaking change

### ISSUE THREAD

**Issue by mjacksonest** [crypto-browserify/parse-asn1#41]
update of asn1 in #37 introduces breaking change
You can see that CI is failing since that change:
https://github.com/crypto-browserify/parse-asn1/commits/v5.1.6
although that failure doesn't appear to prevent publishing of the package.

**Comment by mjacksonest** [comment]
I rolled back to v5.1.5 to address the issue I was having.

**Comment by chiragbhatia94** [comment]
Yes, it is breaking flows in crypto-browserify and webpack too. Needs to be reverted

> update of asn1 in #37 introduces breaking change
> You can see that CI is failing since that change:
> https://github.com/crypto-browserify/parse-asn1/commits/v5.1.6
> although that failure doesn't appear to prevent publishing of the package.

**Comment by AnshulSurana** [comment]
yes, it is breaking flows. rolling back to v5.1.5.

**Comment by calvinmetcalf** [comment]
ok so we had to upgrade the library due to a security vulnerability in the library.  This is only a breaking change in very out of date versions of node that are not supported anymore.  If you are building software based on that you should be aggressively pinning your dependencies with shrink wrap or package-lock.  Like I'm shocked that this is the first instance of `const` to show up here

You're right the ci was failing, but that's only because I hadn't changed the target of those since the iojs era which is 100% not a level of backwards compatibility we support, so I updated the tests in #44 to supported node versions.

**Comment by kiransp84** [comment]
Hi ,

After the new version of parse-asn1 ( 5.1.6)  is released we are getting error while we try to run webpack build. During the webpack build we are invoking Uglifyjs plugin. The version 5.1.6 contains ES6 code , but in previous versions it was ES5 code.  So the UglifyJS plugin is not able to parse the code. Currently our work is halted due to this issue. Can we expect a resolution to this issue at the earliest ?

**Comment by calvinmetcalf** [comment]
you're going to need to pin it to 5.1.5 or switch from ugilfy to something like babel-minify

**Comment by mjacksonest** [comment]
@calvinmetcalf I agree that us poor schlubs stuck on old versions of nodejs need to fend for ourselves, but introducing a breaking change, for whatever reason, in a patch release, breaks the contract. You need to bump the major version with this change. You can change the version of nodejs you support for sure, but that should be done in a major version bump.

**Comment by calvinmetcalf** [comment]
this isn't a library that people depend on directly it's included with browserify/webpack so if we bumped the major, we'd just bump the thing importing it depriving other people of the security fixes

**Comment by tjcampbell** [comment]
@calvinmetcalf the issue is that this will break builds for most Webpack 3 projects as it defaults to minifying with it's own version of UglifyJS which doesn't support es6. Agreed it's an old version, but I don't think it should automatically be nuked because of a few instances of let and const in a nested dependency patch release.

**Comment by calvinmetcalf** [comment]
ok so the problem is that webpack brings this in via other libraries so there's no easy way to make it so that only new versions  of webpack get this.

**Comment by tjrobinson** [comment]
I've been able to work round this for now by using [npm-force-resolutions](https://www.npmjs.com/package/npm-force-resolutions) with the following additions to my `package.json`:

```json
"resolutions": {
  "parse-asn1": "5.1.5"
},
"scripts": {
  "preinstall": "npx npm-force-resolutions"
}
```

I was running into problems because `browserify-sign@4.2.1` (used by `webpack@4.44.1`) has a dependency on `"parse-asn1": "^5.0.0",`

**Comment by sw-uedan** [comment]
@calvinmetcalf 
Hi, how is this issue status now?

I'm the one who faced a breaking build, too, and I've commented on this issue below:
https://github.com/crypto-browserify/parse-asn1/issues/45#issuecomment-697115522

**Comment by ljharb** [comment]
@calvinmetcalf it's not just about old versions of node, it's about old browsers that *most* websites still have to support. Could the `const` be reverted?

**Comment by ljharb** [comment]
v5.1.7 restores support down to node 0.10.
